name: Update develop

on:
  push:
    branches: [master]

jobs:
  update-develop:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 100
      - name: Update the develop branch
        run: git push origin origin/master:develop
